/*
 * Swagger Petstore
 * This is a sample Petstore server.  You can find  out more about Swagger at  [http://swagger.io](http://swagger.io) or on  [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Movie
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-25T07:32:05.010Z")
public class Movie {
  @SerializedName("_id")
  private Long id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("runtimeInMinutes")
  private Long runtimeInMinutes = null;

  @SerializedName("budgetInMillions")
  private Long budgetInMillions = null;

  @SerializedName("boxOfficeRevenueInMillions")
  private Long boxOfficeRevenueInMillions = null;

  @SerializedName("academyAwardNominations")
  private Long academyAwardNominations = null;

  @SerializedName("academyAwardWins")
  private Long academyAwardWins = null;

  @SerializedName("rottenTomatoesScore")
  private Long rottenTomatoesScore = null;

  public Movie id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Movie name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Movie runtimeInMinutes(Long runtimeInMinutes) {
    this.runtimeInMinutes = runtimeInMinutes;
    return this;
  }

   /**
   * Get runtimeInMinutes
   * @return runtimeInMinutes
  **/
  @ApiModelProperty(value = "")
  public Long getRuntimeInMinutes() {
    return runtimeInMinutes;
  }

  public void setRuntimeInMinutes(Long runtimeInMinutes) {
    this.runtimeInMinutes = runtimeInMinutes;
  }

  public Movie budgetInMillions(Long budgetInMillions) {
    this.budgetInMillions = budgetInMillions;
    return this;
  }

   /**
   * Get budgetInMillions
   * @return budgetInMillions
  **/
  @ApiModelProperty(value = "")
  public Long getBudgetInMillions() {
    return budgetInMillions;
  }

  public void setBudgetInMillions(Long budgetInMillions) {
    this.budgetInMillions = budgetInMillions;
  }

  public Movie boxOfficeRevenueInMillions(Long boxOfficeRevenueInMillions) {
    this.boxOfficeRevenueInMillions = boxOfficeRevenueInMillions;
    return this;
  }

   /**
   * Get boxOfficeRevenueInMillions
   * @return boxOfficeRevenueInMillions
  **/
  @ApiModelProperty(value = "")
  public Long getBoxOfficeRevenueInMillions() {
    return boxOfficeRevenueInMillions;
  }

  public void setBoxOfficeRevenueInMillions(Long boxOfficeRevenueInMillions) {
    this.boxOfficeRevenueInMillions = boxOfficeRevenueInMillions;
  }

  public Movie academyAwardNominations(Long academyAwardNominations) {
    this.academyAwardNominations = academyAwardNominations;
    return this;
  }

   /**
   * Get academyAwardNominations
   * @return academyAwardNominations
  **/
  @ApiModelProperty(value = "")
  public Long getAcademyAwardNominations() {
    return academyAwardNominations;
  }

  public void setAcademyAwardNominations(Long academyAwardNominations) {
    this.academyAwardNominations = academyAwardNominations;
  }

  public Movie academyAwardWins(Long academyAwardWins) {
    this.academyAwardWins = academyAwardWins;
    return this;
  }

   /**
   * Get academyAwardWins
   * @return academyAwardWins
  **/
  @ApiModelProperty(value = "")
  public Long getAcademyAwardWins() {
    return academyAwardWins;
  }

  public void setAcademyAwardWins(Long academyAwardWins) {
    this.academyAwardWins = academyAwardWins;
  }

  public Movie rottenTomatoesScore(Long rottenTomatoesScore) {
    this.rottenTomatoesScore = rottenTomatoesScore;
    return this;
  }

   /**
   * Get rottenTomatoesScore
   * @return rottenTomatoesScore
  **/
  @ApiModelProperty(value = "")
  public Long getRottenTomatoesScore() {
    return rottenTomatoesScore;
  }

  public void setRottenTomatoesScore(Long rottenTomatoesScore) {
    this.rottenTomatoesScore = rottenTomatoesScore;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Movie movie = (Movie) o;
    return Objects.equals(this.id, movie.id) &&
        Objects.equals(this.name, movie.name) &&
        Objects.equals(this.runtimeInMinutes, movie.runtimeInMinutes) &&
        Objects.equals(this.budgetInMillions, movie.budgetInMillions) &&
        Objects.equals(this.boxOfficeRevenueInMillions, movie.boxOfficeRevenueInMillions) &&
        Objects.equals(this.academyAwardNominations, movie.academyAwardNominations) &&
        Objects.equals(this.academyAwardWins, movie.academyAwardWins) &&
        Objects.equals(this.rottenTomatoesScore, movie.rottenTomatoesScore);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, runtimeInMinutes, budgetInMillions, boxOfficeRevenueInMillions, academyAwardNominations, academyAwardWins, rottenTomatoesScore);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Movie {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    runtimeInMinutes: ").append(toIndentedString(runtimeInMinutes)).append("\n");
    sb.append("    budgetInMillions: ").append(toIndentedString(budgetInMillions)).append("\n");
    sb.append("    boxOfficeRevenueInMillions: ").append(toIndentedString(boxOfficeRevenueInMillions)).append("\n");
    sb.append("    academyAwardNominations: ").append(toIndentedString(academyAwardNominations)).append("\n");
    sb.append("    academyAwardWins: ").append(toIndentedString(academyAwardWins)).append("\n");
    sb.append("    rottenTomatoesScore: ").append(toIndentedString(rottenTomatoesScore)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

