/*
 * Swagger Petstore
 * This is a sample Petstore server.  You can find  out more about Swagger at  [http://swagger.io](http://swagger.io) or on  [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.MovieQuotes;
import io.swagger.client.model.Movies;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MovieApi
 */
@Ignore
public class MovieApiTest {

    private final MovieApi api = new MovieApi();

    
    /**
     * List of all \&quot;The Lord of the Rings\&quot; movie
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAllMovieTest() throws Exception {
        Movies response = api.getAllMovie();

        // TODO: test validations
    }
    
    /**
     * List of all \&quot;The Lord of the Rings\&quot; movie
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAllMovieQuotesTest() throws Exception {
        Long id = null;
        MovieQuotes response = api.getAllMovieQuotes(id);

        // TODO: test validations
    }
    
}
